// app/(home)/components/LinkTab.tsx
import React from 'react';

import { github, instagram, linkedin, twitter } from '@constant/index';
import { Link } from '@element/Link';

const LinkTab = () => (
  <div className="flex items-center mt-4 space-x-2 rounded-md text-wolgray">
    <div className="flex flex-wrap items-center justify-between w-4/5 pt-6 pb-16 mx-auto text-4xl lg:pb-0 lg:w-full">
      <Link href={`https://instagram.com/${instagram}`}>
        {' '}
        <i className="transition duration-200 bx bxl-instagram text-wolgray hover:text-wolwhite"></i>
      </Link>
      <Link href={`https://twitter.com/${twitter}`}>
        {' '}
        <i className="transition duration-200 bx bxl-twitter text-wolgray hover:text-wolwhite"></i>{' '}
      </Link>
      <Link href={`https://github.com/${github}`}>
        {' '}
        <i className="transition duration-200 bx bxl-github text-wolgray hover:text-wolwhite"></i>{' '}
      </Link>
      <Link href={`https://www.linkedin.com/in/${linkedin}/`}>
        {' '}
        <i className="transition duration-200 bx bxl-linkedin-square text-wolgray hover:text-wolwhite"></i>{' '}
      </Link>
    </div>
  </div>
);

export default LinkTab;

// src/components/LinkTab.vue
<template>
    <div class="flex items-center  space-x-2 rounded-md text-wolgray mt-4">
            <div class="pt-6 pb-16 lg:pb-0 w-4/5 lg:w-full mx-auto flex flex-wrap items-center justify-between text-4xl">
				<a  href="https://instagram.com/thewolmer" target="_blank"> <i class='bx bxl-instagram text-wolgray hover:text-wolwhite' ></i></a>
				<a  href="https://twitter.com/thewolmer" target="_blank"> <i class='bx bxl-twitter text-wolgray hover:text-wolwhite' ></i> </a>
				<a  href="https://github.com/thewolmer" target="_blank"> <i class='bx bxl-github text-wolgray hover:text-wolwhite' ></i> </a>
				<a  href="https://www.linkedin.com/in/thewolmer/" target="_blank"> <i class='bx bxl-linkedin-square text-wolgray hover:text-wolwhite' ></i> </a>
				<!-- <a  href="https://buymeacoffee.com/thewolmer" target="_blank"> <i class='bx bx-coffee-togo text-wolgray hover:text-wolwhite' ></i> </a> -->
			</div>
        </div>
</template>

<script>
export default {
    name:'LinkTab',
}
</script>
